import { createRemoteJWKSet, jwtVerify, type JWTVerifyGetKey } from 'jose';
import { timingSafeEqual } from 'node:crypto';
import type { RequestHandler } from 'express';
import type { TerminalState } from '../src/types.js';

export function hostedSettings(env: NodeJS.ProcessEnv) {
  if (env.HOSTING_MODE !== 'cloud') return null;
  if (!env.SUPABASE_DATABASE_URL || (env.ORIGIN_SECRET?.length ?? 0) < 32) throw new Error('Cloud requires durable storage and an origin secret');
  const origin = new URL(env.PUBLIC_ORIGIN || '');
  if (origin.protocol !== 'https:' || origin.origin !== env.PUBLIC_ORIGIN) throw new Error('Exact HTTPS frontend origin required');
  const issuer = env.CF_ACCESS_ISSUER;
  if (issuer && !/^https:\/\/[a-z0-9-]+\.cloudflareaccess\.com$/.test(issuer)) throw new Error('Invalid Access issuer');
  return { bind: '0.0.0.0', origin: origin.origin, secret: env.ORIGIN_SECRET!,
    policy: issuer && env.CF_ACCESS_AUDIENCE && env.OPERATOR_EMAIL ? { issuer, audience: env.CF_ACCESS_AUDIENCE, email: env.OPERATOR_EMAIL.toLowerCase() } : null };
}
export async function authorizeOperator(token: string | undefined, policy: {issuer:string;audience:string;email:string}, keys: JWTVerifyGetKey) {
  if (!token || token.length > 16384) return false;
  try {
    const { payload } = await jwtVerify(token, keys, { issuer: policy.issuer, audience: policy.audience, algorithms: ['RS256'], requiredClaims: ['exp','iat','sub','email'] });
    return typeof payload.email === 'string' && payload.email.toLowerCase() === policy.email;
  } catch { return false; }
}
const matchesSecret = (provided: string | undefined, expected: string) => {
  if (!provided) return false;
  const a = Buffer.from(provided), b = Buffer.from(expected);
  return a.length === b.length && timingSafeEqual(a,b);
};
export function cloudAccess(settings: NonNullable<ReturnType<typeof hostedSettings>>): RequestHandler {
  const keys = settings.policy ? createRemoteJWKSet(new URL(settings.policy.issuer + '/cdn-cgi/access/certs'), {timeoutDuration:5000,cooldownDuration:30000,cacheMaxAge:600000}) : null;
  return async (req,res,next) => {
    res.setHeader('Cache-Control','no-store');
    res.setHeader('X-Content-Type-Options','nosniff');
    res.setHeader('Referrer-Policy','no-referrer');
    res.setHeader('X-Frame-Options','DENY');
    if (req.path === '/api/health' && ['GET','HEAD'].includes(req.method)) return next();
    // A private server-to-server secret prevents direct origin bypass. Never sent to browser JS.
    if (!matchesSecret(req.get('x-jev-origin-secret'),settings.secret)) return void res.status(403).json({error:'Origin access denied'});
    res.locals.operator = !!(keys && settings.policy && await authorizeOperator(req.get('cf-access-jwt-assertion'),settings.policy,keys));
    if (!['GET','HEAD'].includes(req.method)) {
      if (!res.locals.operator) return void res.status(403).json({error:'Operator authentication required'});
      if (req.headers.origin !== settings.origin || !req.is('application/json')) return void res.status(403).json({error:'Same-origin JSON request required'});
    }
    next();
  };
}

export function publicState(s: TerminalState): TerminalState {
  const decisions = s.decisions.map(d => {
    const { intent: _intent, executionContext: _context, ...record } = structuredClone(d);
    record.memories = record.memories.map(m => m.localProvenance?.episodeIds.length ? m : { ...m, slug:'',title:'Private memory context',summary:'This retrieved page was not generated by the public trading journal. Its content is visible only to the operator.' });
    return record;
  });
  return {
    edition:s.edition,memoryProvider:s.memoryProvider,workerActive:s.workerActive,
    assessmentService:s.assessmentService ? {...s.assessmentService} : undefined,
    revision:s.revision,approvedPools:[...s.approvedPools],running:s.running,halted:s.halted,lastCycleAt:s.lastCycleAt,
    ledger:{...structuredClone(s.ledger),consumedDecisions:[]},decisions,
    memoryEpisodes:s.memoryEpisodes?.map(e=>({...structuredClone(e),content:{summary:e.summary,publicView:true},capture:{...e.capture,sourceId:undefined}})),
    pools:structuredClone(s.pools),providers:s.providers.map(p=>({name:p.name,state:p.state,checkedAt:p.checkedAt,detail:p.state === 'ready' ? 'Connected' : p.state === 'error' ? 'Provider unavailable' : 'Awaiting verification'})),
    busy:s.busy,discoveryError:s.discoveryError,exitError:s.exitError,database:'Durable cloud storage',
    sdk:{version:s.sdk.version,chainId:s.sdk.chainId,walletAddress:null,registration:{}},liveBlockers:[...s.liveBlockers],access:{operator:false},
  };
}

// Shared across all visitors; failures consume budget and are cached too.
export class SharedReadCache {
  private entries = new Map<string,{at:number;value?:unknown;error?:true;pending?:Promise<unknown>}>();
  private attempts: number[] = [];
  constructor(private maxCalls=10,private ttl=60000,private now=Date.now) {}
  async read<T>(key:string,load:()=>Promise<T>):Promise<T> {
    const at=this.now(),existing=this.entries.get(key);
    if(existing?.pending) return existing.pending as Promise<T>;
    if(existing && at-existing.at<this.ttl){if(existing.error)throw new Error('Temporarily unavailable');return structuredClone(existing.value) as T;}
    this.attempts=this.attempts.filter(t=>at-t<60000);
    if(this.attempts.length>=this.maxCalls)throw new Error('Read budget exhausted; retry shortly');
    this.attempts.push(at);
    const entry:{at:number;value?:unknown;error?:true;pending?:Promise<unknown>}={at};
    const task=Promise.resolve().then(load).then(value=>{entry.value=structuredClone(value);entry.at=this.now();return value;},()=>{entry.error=true;entry.at=this.now();throw new Error('Temporarily unavailable');}).finally(()=>{delete entry.pending;});
    entry.pending=task;
    if(this.entries.size>=100) {const expired=[...this.entries].find(([,e])=>!e.pending);if(expired)this.entries.delete(expired[0]);}
    this.entries.set(key,entry);
    return task;
  }
}
